resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: my-backend
  newName: 053447641011.dkr.ecr.eu-west-2.amazonaws.com/my-backend
  newTag: backend-976296b45ee0d4648409558bce75a3bc340432f0
