resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: my-backend
  newName: 053447641011.dkr.ecr.eu-west-2.amazonaws.com/my-backend
  newTag: backend-122a6e57b9c9af675153fab1fbf563ab72b11ccd
