apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.0.0 
    helm:
      valueFiles:
      - $values/blob/main/charts/grafana/values.yaml
  - repoURL: https://github.com/Hanz-ala1/gitops/apps/monitoring/base/values.yaml
    targetRevision: feature/prometheus-grafana
    ref: grafana-values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true