apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.0.0 
    helm:
      values: |
        admin:
          existingSecret: grafana-admin
          userKey: admin-user
          passwordKey: admin-password

        # using ClusterIP because we're routing via Ingress 
        service:
          type: ClusterIP
          port: 80

        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            acme.cert-manager.io/http01-edit-in-place: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - grafana.thriveai.website
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.thriveai.website

        persistence:
          enabled: false
          size: 1Gi
          storageClassName: gp2

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true