alertmanager:
  enabled: false

server:
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - promethus.thriveai.website
    tls:
      - secretName: prometheus-tls
        hosts:
          - promethus.thriveai.website