apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: prometheus
    targetRevision: 15.7.0 
    helm:
      valueFiles:
      - $values/apps/monitoring/base/prometheus_values.yaml
  - repoURL: https://github.com/Hanz-ala1/gitops
    targetRevision: feature/prometheus-grafana
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true