admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - grafana.thriveai.website
  path: /
  pathType: Prefix
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.thriveai.website

# persistence
persistence:
  enabled: false
  size: 1Gi
  storageClassName: gp2