apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
# kustomize will use the image name frontend to find the image to replace
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
