resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
- ingress-certmanager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: my-frontend
  newName: 053447641011.dkr.ecr.eu-west-2.amazonaws.com/my-frontend
  newTag: frontend-df821fa6c13c8aa463d924107b1d9b1b009cb85d
