resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
- ingress-certmanager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: my-frontend
  newName: 053447641011.dkr.ecr.eu-west-2.amazonaws.com/my-frontend
  newTag: frontend-fc600b9e0a60f0f540b540551e3b3e398eacea69
