resources:
- ../../base

patchesStrategicMerge:
- patch-deployment.yaml
- ingress-certmanager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: my-frontend
  newName: 053447641011.dkr.ecr.eu-west-2.amazonaws.com/my-frontend
  newTag: frontend-60affa1c555ba88bb545ccb4b8425705bf41bfd5
